### ISSUE TITLE
"Ubiquity admin" does not install required composer dependencies

### ISSUE THREAD

**Issue by Tantriss** [phpMv/ubiquity-devtools#13]
Hi, again ^^

I found that if you installed you project without the `-a` param (without admin), trying to install it after with `Ubiquity admin` will not do anything.

The piece of code (function adminInstall) which require everything the admin needs seems to exists only for the purpose of `-a` flag of the `Ubiquity new` commands as it only push to an array of requires (`$toolsConfig`) but does not actually call composer.

So if you call it directly : `Ubiquity admin`, it does nothing.

We should make this function standalone in a way it should directly call composer to install these dependencies.
It will probably slow a little the `Ubiquity new -a` command as 2 composer installs (actually 3 as we can't `require` and `require-dev` in a single command) will happen if we don't want to duplicate any code but that should not have a big impact.

I don't really like this solution, will probably open a PR with something else or if you guys got anything better I'm in !

Tantriss.

**Comment by jcheron** [comment]
I think that we shouldn't modify the `create` method (so Ubiquity new with `-a` option), since its logic is to create the `composer.json` file (badly formatted by the way...)

It is necessary to create a new method, using the `$toolsConfig array["composer"]`, and requesting the necessary `composer require...` commands... (with the php `system` command).
Then call this method from `adminInstall`.
